#!/bin/bash

container_name='spring_env'

docker_start(){
    docker run -p 0.0.0.0:8080:8080 -p 0.0.0.0:8090:8090 -v `pwd`/spring-petclinic:/spring-petclinic --name $container_name tinkerwaredockerhub/tinker_spring:latest
}

docker_restart(){
    docker stop $container_name
    docker start -a $container_name
    return 0
}


if [ $# -eq 0 ] || [ "$1" = "start" ];
then
	if ! docker_start 2> /dev/null 
	then
	    docker_restart
	fi
fi

if [ "$1" = "stop" ]; then
	docker stop $container_name
	echo "container stopped"
fi


if [ $# -eq 2 ] && [ "$1" = "restart" ] && [ "$2" = "--force" ]; then
	docker stop $container_name
	docker rm $container_name
	docker_start

elif [ "$1" = "restart" ]; then
	docker_restart
fi

