#!/bin/bash


docker_start(){
    docker-compose up
}

docker_restart(){
    docker-compose stop
    docker-compose up
    return 0
}


if [ $# -eq 0 ] || [ "$1" = "start" ];
then
	if ! docker_start 
	then
	    docker_restart
	fi
fi

if [ "$1" = "stop" ]; then
	docker-compose stop
	echo "containers stopped"
fi


if [ $# -eq 2 ] && [ "$1" = "restart" ] && [ "$2" = "--force" ]; then
	docker-compose stop
	docker-compose start

elif [ "$1" = "restart" ]; then
	docker_restart
fi

